# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM openjdk:17
WORKDIR /app
COPY --from=builder /app/target/Computer-sell.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
EXPOSE 8080
