spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: Computer_sell
    server: ${COMPUTER_SELL:https://localhost:${server.port}}
    title: Backend service
    version: 1.0.0

jwt:
  secretKey: xyz@123